apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: worker-2
servers: 1
agents: 0
image: rancher/k3s:v1.28.5-k3s1
network: k3d-argocd-network
ports:
  - port: 8082:80
    nodeFilters:
      - loadbalancer
  - port: 8446:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
